= Lokaasete ekstreemumpunktide tuvastamine graafil
Karl Rapur, Tiit Vaino
v1.0, 2022-01-06


Töö eesmärk on luua masinõppe algoritm, mis suudab pildil oleval graafil osutada lokaalsetele ekstreemumitele.
Valmis mudelile saab anda ette ükskõik, millise graafiku mis pärineb WolframAlpha keskkonnast või sarnaneb suuremal
määral sealsete graafikutega. Lokaalseid ekstreemumpunkte saab matemaatikas käsitsi välja arvutada,
kuid tegelikkuses on teema oluliselt lihtsam ning pildi peal on võimalik umbmääraselt punkti asukohta alati määrata,
sõltumata funktsiooni keerukusest. Seetõttu tundub see sobilik ülesannete masinõppe jaoks.

== Kasutatud ideed:
* Funktsioonide genereerimine
* Andmete pärimine WolframAlphast - Andmete pärimise idee võtsime juturobotite praktikumidest,
kuid JavaScripti vajaduse tõttu lõime täiesti oma koodi ja loogika.
* Pilditöötlus - Omavajaduste järgi loodud.
* Pildil mustrisobitamine - Töös kasutatakse pisemat sorti mustri sobitamist,
et tuvastada arvutatud piltidel ekstreemumeid. Idee pärineb praktikumidest.
* Tehisnärvivõrgud
* LineaarneRegresioon - Ei andnud sobivat tulemust.

== Töö panus

Kogu algandmete tootmine on loodud meie endi poolt. Kodutöös pole selliseid osi, millele kohta viidata välismaterjalidele.
Teema oli võõras ning internetist ei leidnud palju abi.

Ainuüksi andmete kättesaamiseks kulus korralikult üle 10 tunni tööd. Andmete kokku scrape'imine oli väga tülikas.
Siis selgus, et punase täpuga oskab AI väga täpselt ennustada, mistõttu pidime leidma graafikud ilma punaste täppideta.
Selliseid graafikuid ei leidunud, mistõttu eemladasime koodi teel punased täpid ja joonistasime jooned asemele.

Palju hingi, verd ja pisaraid.

Lõpptulemust ei saavutatud, sest erinevad treenitud mudelid ei suutnud korrektselt ennustada.

== Testimise võimalused
Kogu rakendus on võimeline ennast ise looma ja välja õpetama.
Selleks tuleb jooksutada järgnevaid käsklusi järestikku.
[source, python]
----
# Paigaldab kõik vajalikud pip moodulid.
pip install -r requirements.txt

# Genereerib 1000 erinevat polunoom funktsiooni.
python generate_func.py 1000

# Laadib alla WolframAlphast 1000 funktsiooni ekstreemum punktidega graafikud.
# Kui ei leidu, siis jätab tõmbamata.
python plot_scraper.py

# Leiab piltidelt ekstreemumpunktide koordinaadid pikslite alusel.
python coordinates_finder.py

# Loob testandmete, kus on ekstreemumpunkt kaotatud.
python dot_remover.py

# Töötleb pildid masinõppeks sobivale kujule.
python image_processing.py

----

Kiiruse huvides on kodutöös kaasa pandud kogu `build` kausta sisu ning
eespool mainitud käsklusi tegelikkuses jooksutama ei pea. Graafikute allalaadimine on ajaliselt väga kulukas töö.

Mudeli õpetamiseks on järgnev käsklus.

[source, python]
----
# Teostab masinõppe
python ai_trainer_predicter.py
----


Katsetamine
[source, python]
----
# Katsetamine
python ai.py 'file_path'
----


== Töökäigu kirjeldus.

Andmete kättesaamiseks tegime esmalt funktsioonide genreerimise.
Loodud polünnomaalsed funktsioonid kirjutatakse faili.

Funktsioonide faili põhjal tõmmatakse alla WolframAlphast vastavad funktsioonid.
Kui neid ei leidu, siis ei laeta alla. Seega pilte on vähem kui funktsioone.

Piltidelt leitakse openCV abil ekstreemumpunktide koordinaadid ja kirjutatakse faili.

Kõik pildid töödeldakse väiksemaks ja halli skaalale. Muudatused viiakse läbi ka leitud koordinaatides.


Peame ausalt tunnistama, et teema oli üle meie oskuste.
Andmete kättesaamine osutus väga keerukaks ning võttis meeletus koguses aega.
AI välja õpetamiseks me ei osanud andmeid enda jaoks sobivale kujule saada.
Lineaarse regresiooniga proovides ennustas mudel ebamääraseid andmeid. Suur probleem oli see,
et ühel graafikul võis olla mitu ekstreemumpunkti.

Teine lähenemine oli tehisnärvivõrkudega. Proovisime saada väljundiks
pidliga sama suurt massiivi, kus igale piksile vastaks mingi kindluse väärtus.
See ei andnud soovitud tulemust, sest kõikide pikslite korral olid väärtused 0.2 ringis madalad.
Mudelit treenides oli täpsus kõrge, kuid see ei olnud koosokõlas tulemusega.

Ajaline kulu on kahe autori peale kokku ligemale 25-30 tundi.
Me ei suutunud saavutada soovitud eesmärki, kuid töö käigus õppisime palju ning oskame enam-vähem määratleda enda vigu.
